#!/bin/zsh

# Source the .zshrc file to load all configurations and functions
source /Users/clement2/.dotfiles/stow/zsh/setup/gitsetup

# Example pre-commit hook script
# This script will echo a message before allowing a commit

# fileList=$(gitListNamesOfAllModifiedFiles | grep -E '.kt$|.kts$') ;
# echo $fileList | xargs ktlint >/dev/null 2>&1
# if [ $? -ne 0 ]; then
#     echo "Linting errors found.... --> will try to fix it automatically..."
#     echo $fileList | xargs ktlint --format >/dev/null 2>&1  && echo "Linting errors fixed successfully... but please check the changes before commiting"
#     exit 1 
# fi

# If everything is fine, exit with 0
exit 0
